---
layout: main
title: Goozbach Presentations
name: home
---

## Presentatiosn given by Goozbach

* [Acme: A User Interface for Programmers](/Acme-A-User-Interface-for-Programmers)

* [A BASHful Adventurer](/A-BASHful-Adventurer)



